### ISSUE TITLE
component animation

### ISSUE THREAD

**Issue by mkoczorowski** [AckerApple/ack-angular-fx#1]
Is it possible to animate component enter / leave (create/destroy) ?

**Comment by AckerApple** [comment]
Your question seems too simple, you must be asking something more complicated. Essentially this package is built to do exactly what you are asking. But I must assume you've seen the docs and the examples page so perhaps you are asking something else?

Yes, this package is made for adding animation definitions to components and then typically animated ngIf elements.

**Comment by mkoczorowski** [comment]
ah perfect. Great Work btw!
